/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_opengl_WindowsDisplay */

#ifndef _Included_org_lwjgl_opengl_WindowsDisplay
#define _Included_org_lwjgl_opengl_WindowsDisplay
#ifdef __cplusplus
extern "C" {
#endif
#undef org_lwjgl_opengl_WindowsDisplay_GAMMA_LENGTH
#define org_lwjgl_opengl_WindowsDisplay_GAMMA_LENGTH 256L
#undef org_lwjgl_opengl_WindowsDisplay_WM_MOUSEMOVE
#define org_lwjgl_opengl_WindowsDisplay_WM_MOUSEMOVE 512L
#undef org_lwjgl_opengl_WindowsDisplay_WM_LBUTTONDOWN
#define org_lwjgl_opengl_WindowsDisplay_WM_LBUTTONDOWN 513L
#undef org_lwjgl_opengl_WindowsDisplay_WM_LBUTTONUP
#define org_lwjgl_opengl_WindowsDisplay_WM_LBUTTONUP 514L
#undef org_lwjgl_opengl_WindowsDisplay_WM_LBUTTONDBLCLK
#define org_lwjgl_opengl_WindowsDisplay_WM_LBUTTONDBLCLK 515L
#undef org_lwjgl_opengl_WindowsDisplay_WM_RBUTTONDOWN
#define org_lwjgl_opengl_WindowsDisplay_WM_RBUTTONDOWN 516L
#undef org_lwjgl_opengl_WindowsDisplay_WM_RBUTTONUP
#define org_lwjgl_opengl_WindowsDisplay_WM_RBUTTONUP 517L
#undef org_lwjgl_opengl_WindowsDisplay_WM_RBUTTONDBLCLK
#define org_lwjgl_opengl_WindowsDisplay_WM_RBUTTONDBLCLK 518L
#undef org_lwjgl_opengl_WindowsDisplay_WM_MBUTTONDOWN
#define org_lwjgl_opengl_WindowsDisplay_WM_MBUTTONDOWN 519L
#undef org_lwjgl_opengl_WindowsDisplay_WM_MBUTTONUP
#define org_lwjgl_opengl_WindowsDisplay_WM_MBUTTONUP 520L
#undef org_lwjgl_opengl_WindowsDisplay_WM_MBUTTONDBLCLK
#define org_lwjgl_opengl_WindowsDisplay_WM_MBUTTONDBLCLK 521L
#undef org_lwjgl_opengl_WindowsDisplay_WM_MOUSEWHEEL
#define org_lwjgl_opengl_WindowsDisplay_WM_MOUSEWHEEL 522L
#undef org_lwjgl_opengl_WindowsDisplay_WM_QUIT
#define org_lwjgl_opengl_WindowsDisplay_WM_QUIT 18L
#undef org_lwjgl_opengl_WindowsDisplay_WM_SYSCOMMAND
#define org_lwjgl_opengl_WindowsDisplay_WM_SYSCOMMAND 274L
#undef org_lwjgl_opengl_WindowsDisplay_WM_PAINT
#define org_lwjgl_opengl_WindowsDisplay_WM_PAINT 15L
#undef org_lwjgl_opengl_WindowsDisplay_SC_SIZE
#define org_lwjgl_opengl_WindowsDisplay_SC_SIZE 61440L
#undef org_lwjgl_opengl_WindowsDisplay_SC_MOVE
#define org_lwjgl_opengl_WindowsDisplay_SC_MOVE 61456L
#undef org_lwjgl_opengl_WindowsDisplay_SC_MINIMIZE
#define org_lwjgl_opengl_WindowsDisplay_SC_MINIMIZE 61472L
#undef org_lwjgl_opengl_WindowsDisplay_SC_MAXIMIZE
#define org_lwjgl_opengl_WindowsDisplay_SC_MAXIMIZE 61488L
#undef org_lwjgl_opengl_WindowsDisplay_SC_NEXTWINDOW
#define org_lwjgl_opengl_WindowsDisplay_SC_NEXTWINDOW 61504L
#undef org_lwjgl_opengl_WindowsDisplay_SC_PREVWINDOW
#define org_lwjgl_opengl_WindowsDisplay_SC_PREVWINDOW 61520L
#undef org_lwjgl_opengl_WindowsDisplay_SC_CLOSE
#define org_lwjgl_opengl_WindowsDisplay_SC_CLOSE 61536L
#undef org_lwjgl_opengl_WindowsDisplay_SC_VSCROLL
#define org_lwjgl_opengl_WindowsDisplay_SC_VSCROLL 61552L
#undef org_lwjgl_opengl_WindowsDisplay_SC_HSCROLL
#define org_lwjgl_opengl_WindowsDisplay_SC_HSCROLL 61568L
#undef org_lwjgl_opengl_WindowsDisplay_SC_MOUSEMENU
#define org_lwjgl_opengl_WindowsDisplay_SC_MOUSEMENU 61584L
#undef org_lwjgl_opengl_WindowsDisplay_SC_KEYMENU
#define org_lwjgl_opengl_WindowsDisplay_SC_KEYMENU 61696L
#undef org_lwjgl_opengl_WindowsDisplay_SC_ARRANGE
#define org_lwjgl_opengl_WindowsDisplay_SC_ARRANGE 61712L
#undef org_lwjgl_opengl_WindowsDisplay_SC_RESTORE
#define org_lwjgl_opengl_WindowsDisplay_SC_RESTORE 61728L
#undef org_lwjgl_opengl_WindowsDisplay_SC_TASKLIST
#define org_lwjgl_opengl_WindowsDisplay_SC_TASKLIST 61744L
#undef org_lwjgl_opengl_WindowsDisplay_SC_SCREENSAVE
#define org_lwjgl_opengl_WindowsDisplay_SC_SCREENSAVE 61760L
#undef org_lwjgl_opengl_WindowsDisplay_SC_HOTKEY
#define org_lwjgl_opengl_WindowsDisplay_SC_HOTKEY 61776L
#undef org_lwjgl_opengl_WindowsDisplay_SC_DEFAULT
#define org_lwjgl_opengl_WindowsDisplay_SC_DEFAULT 61792L
#undef org_lwjgl_opengl_WindowsDisplay_SC_MONITORPOWER
#define org_lwjgl_opengl_WindowsDisplay_SC_MONITORPOWER 61808L
#undef org_lwjgl_opengl_WindowsDisplay_SC_CONTEXTHELP
#define org_lwjgl_opengl_WindowsDisplay_SC_CONTEXTHELP 61824L
#undef org_lwjgl_opengl_WindowsDisplay_SC_SEPARATOR
#define org_lwjgl_opengl_WindowsDisplay_SC_SEPARATOR 61455L
#undef org_lwjgl_opengl_WindowsDisplay_SM_CXCURSOR
#define org_lwjgl_opengl_WindowsDisplay_SM_CXCURSOR 13L
#undef org_lwjgl_opengl_WindowsDisplay_SIZE_RESTORED
#define org_lwjgl_opengl_WindowsDisplay_SIZE_RESTORED 0L
#undef org_lwjgl_opengl_WindowsDisplay_SIZE_MINIMIZED
#define org_lwjgl_opengl_WindowsDisplay_SIZE_MINIMIZED 1L
#undef org_lwjgl_opengl_WindowsDisplay_SIZE_MAXIMIZED
#define org_lwjgl_opengl_WindowsDisplay_SIZE_MAXIMIZED 2L
#undef org_lwjgl_opengl_WindowsDisplay_WM_SIZE
#define org_lwjgl_opengl_WindowsDisplay_WM_SIZE 5L
#undef org_lwjgl_opengl_WindowsDisplay_WM_ACTIVATE
#define org_lwjgl_opengl_WindowsDisplay_WM_ACTIVATE 6L
#undef org_lwjgl_opengl_WindowsDisplay_WA_INACTIVE
#define org_lwjgl_opengl_WindowsDisplay_WA_INACTIVE 0L
#undef org_lwjgl_opengl_WindowsDisplay_WA_ACTIVE
#define org_lwjgl_opengl_WindowsDisplay_WA_ACTIVE 1L
#undef org_lwjgl_opengl_WindowsDisplay_WA_CLICKACTIVE
#define org_lwjgl_opengl_WindowsDisplay_WA_CLICKACTIVE 2L
#undef org_lwjgl_opengl_WindowsDisplay_SW_SHOWMINNOACTIVE
#define org_lwjgl_opengl_WindowsDisplay_SW_SHOWMINNOACTIVE 7L
#undef org_lwjgl_opengl_WindowsDisplay_SW_SHOWDEFAULT
#define org_lwjgl_opengl_WindowsDisplay_SW_SHOWDEFAULT 10L
#undef org_lwjgl_opengl_WindowsDisplay_SW_RESTORE
#define org_lwjgl_opengl_WindowsDisplay_SW_RESTORE 9L
/* Inaccessible static: current_display */
/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    nCreateWindow
 * Signature: (Lorg/lwjgl/opengl/DisplayMode;ZII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_WindowsDisplay_nCreateWindow
  (JNIEnv *, jobject, jobject, jboolean, jint, jint);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    nDestroyWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_WindowsDisplay_nDestroyWindow
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    resetCursorClipping
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_WindowsDisplay_resetCursorClipping
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    setupCursorClipping
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_WindowsDisplay_setupCursorClipping
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    nSwitchDisplayMode
 * Signature: (Lorg/lwjgl/opengl/DisplayMode;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_WindowsDisplay_nSwitchDisplayMode
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    showWindow
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_WindowsDisplay_showWindow
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    setForegroundWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_WindowsDisplay_setForegroundWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    setFocus
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_WindowsDisplay_setFocus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    nResetDisplayMode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_WindowsDisplay_nResetDisplayMode
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    convertToNativeRamp
 * Signature: (Ljava/nio/FloatBuffer;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_opengl_WindowsDisplay_convertToNativeRamp
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    getCurrentGammaRamp
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_opengl_WindowsDisplay_getCurrentGammaRamp
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    nSetGammaRamp
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_WindowsDisplay_nSetGammaRamp
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    nGetVersion
 * Signature: (Ljava/lang/String;)Lorg/lwjgl/opengl/WindowsFileVersion;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_opengl_WindowsDisplay_nGetVersion
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    getCurrentDisplayMode
 * Signature: ()Lorg/lwjgl/opengl/DisplayMode;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_opengl_WindowsDisplay_getCurrentDisplayMode
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    setTitle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_WindowsDisplay_setTitle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    nUpdate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_WindowsDisplay_nUpdate
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    nReshape
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_WindowsDisplay_nReshape
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    getAvailableDisplayModes
 * Signature: ()[Lorg/lwjgl/opengl/DisplayMode;
 */
JNIEXPORT jobjectArray JNICALL Java_org_lwjgl_opengl_WindowsDisplay_getAvailableDisplayModes
  (JNIEnv *, jobject);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    nSetCursorPosition
 * Signature: (IIZ)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_WindowsDisplay_nSetCursorPosition
  (JNIEnv *, jclass, jint, jint, jboolean);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    setNativeCursor
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_WindowsDisplay_setNativeCursor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    getSystemMetrics
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_WindowsDisplay_getSystemMetrics
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    getDllInstance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_lwjgl_opengl_WindowsDisplay_getDllInstance
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    getHwnd
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_lwjgl_opengl_WindowsDisplay_getHwnd
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    nCreateCursor
 * Signature: (IIIIILjava/nio/IntBuffer;ILjava/nio/IntBuffer;I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_lwjgl_opengl_WindowsDisplay_nCreateCursor
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jobject, jint, jobject, jint);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    destroyCursor
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_opengl_WindowsDisplay_destroyCursor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    nGetPbufferCapabilities
 * Signature: (Lorg/lwjgl/opengl/PixelFormat;)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_WindowsDisplay_nGetPbufferCapabilities
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    nSetWindowIcon16
 * Signature: (Ljava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_WindowsDisplay_nSetWindowIcon16
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    nSetWindowIcon32
 * Signature: (Ljava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_WindowsDisplay_nSetWindowIcon32
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_lwjgl_opengl_WindowsDisplay
 * Method:    transformY
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_opengl_WindowsDisplay_transformY
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
