/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lwjgl_devil_ILNative */

#ifndef _Included_org_lwjgl_devil_ILNative
#define _Included_org_lwjgl_devil_ILNative
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: JNI_LIBRARY_NAME */
#undef org_lwjgl_devil_ILNative_JNI_VERSION
#define org_lwjgl_devil_ILNative_JNI_VERSION 2L
/* Inaccessible static: class_00024org_00024lwjgl_00024devil_00024IL */
/* Inaccessible static: class_00024org_00024lwjgl_00024devil_00024ILU */
/* Inaccessible static: class_00024org_00024lwjgl_00024devil_00024ILUT */
/*
 * Class:     org_lwjgl_devil_ILNative
 * Method:    initNativeStubsIL
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILNative_initNativeStubsIL
  (JNIEnv *, jclass, jclass);

/*
 * Class:     org_lwjgl_devil_ILNative
 * Method:    resetNativeStubsIL
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILNative_resetNativeStubsIL
  (JNIEnv *, jclass, jclass);

/*
 * Class:     org_lwjgl_devil_ILNative
 * Method:    nCreateIL
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILNative_nCreateIL
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_lwjgl_devil_ILNative
 * Method:    nDestroyIL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILNative_nDestroyIL
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_ILNative
 * Method:    getNativeLibraryVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lwjgl_devil_ILNative_getNativeLibraryVersion
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_ILNative
 * Method:    initNativeStubsILU
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILNative_initNativeStubsILU
  (JNIEnv *, jclass, jclass);

/*
 * Class:     org_lwjgl_devil_ILNative
 * Method:    resetNativeStubsILU
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILNative_resetNativeStubsILU
  (JNIEnv *, jclass, jclass);

/*
 * Class:     org_lwjgl_devil_ILNative
 * Method:    nCreateILU
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILNative_nCreateILU
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_lwjgl_devil_ILNative
 * Method:    nDestroyILU
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILNative_nDestroyILU
  (JNIEnv *, jclass);

/*
 * Class:     org_lwjgl_devil_ILNative
 * Method:    initNativeStubsILUT
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILNative_initNativeStubsILUT
  (JNIEnv *, jclass, jclass);

/*
 * Class:     org_lwjgl_devil_ILNative
 * Method:    resetNativeStubsILUT
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILNative_resetNativeStubsILUT
  (JNIEnv *, jclass, jclass);

/*
 * Class:     org_lwjgl_devil_ILNative
 * Method:    nCreateILUT
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILNative_nCreateILUT
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     org_lwjgl_devil_ILNative
 * Method:    nDestroyILUT
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lwjgl_devil_ILNative_nDestroyILUT
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
